spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://office.leevi.co.kr:49886/?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Phantom@222
  mvc:
    converters:
      preferred-json-mapper: gson

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: validate
